services:
    mongod-service:
        container_name: "mongod-service"
        image: mongo:latest
        ports:
            - "30101:27010"
        command: mongod --replSet cnf-serv --configsvr --port 27010
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:latest
        depends_on:
            - "mongod-service"
        links:
            - mongod-service:mongod-service
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongod-service
            - RS=cnf-serv
            - PORT=27010
        entrypoint: ["/scripts/setup-cnf.sh"]
