version: "2"

services:
    mongosh-service:
        container_name: "mongosh-service"
        image: mongo:latest
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mongo:latest
        depends_on:
            - "mongosh-service"
        links:
            - mongosh-service:mongosh-service
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongosh-service
            - RS=rs1
        entrypoint: ["/scripts/setup.sh"]
